 $( function() {
    var availableTags = [
       "Agh University Of Science And Technology",
"Aalborg University",
"Aalto University",
"Aarhus University",
"Abia State University",
"Academy Of Arts",
"Academy Of Economic Studies Of Moldova",
"Acadia University",
"Addis Ababa University",
"Adventist University Of Central Africa",
"Adventist University Of The Philippines",
"Africa International University",
"Africa Nazarene University",
"Africa University",
"Aga Khan University",
"Agricultural University Of Athens",
"Agroparistech",
"Ahmadu Bello University",
"Ain Shams University",
"Ajayi Crowther University",
"Al Akhawayn University",
"Al-Baath University",
"Al-Farabi Kazakh National University",
"Alagappa University",
"Aligarh Muslim University",
"Altai State University",
"Ambo University",
"Ambrose Alli University",
"American College Of Greece",
"American College Of Thessaloniki",
"American Graduate School In Paris",
"American University In Bulgaria",
"American University Of Afghanistan",
"American University Of Antigua",
"American University Of Armenia",
"American University Of Beirut",
"American University Of Central Asia",
"American University Of Sharjah",
"Amirkabir University Of Technology",
"Amur State University",
"Anadolu University",
"Andalas University",
"Anglo-American University",
"Ankara University",
"Anna University",
"Arba Minch University",
"Aristotle University Of Thessaloniki",
"Arizona State University",
"Armenian State University Of Economics",
"Asian University Of Bangladesh",
"Assumption University",
"Aston University",
"Astrakhan State University",
"Athabasca University",
"Athens University Of Economics And Business",
"Auckland University Of Technology",
"Azerbaijan State Economic University",
"Brac University",
"Babes-Bolyai University",
"Bahria University",
"Baku Slavic University",
"Balochistan University Of Engineering And Technology Khuzdar",
"Banaras Hindu University",
"Bandung Institute Of Technology",
"Bangalore University",
"Bangor University",
"Bar-Ilan University",
"Barcelona Graduate School Of Economics",
"Bashkir State University",
"Bath Spa University",
"Beijing Institute Of Technology",
"Beijing International Studies University",
"Beijing Language And Culture University",
"Beijing Normal University",
"Beijing Sport University",
"Belarusian National Technical University",
"Belarusian State Medical University",
"Belarusian State University",
"Bells University Of Technology",
"Berhampur University",
"Bharathidasan University",
"Bindura University Of Science Education",
"Bircham International University",
"Birkbeck, University Of London",
"Birmingham City University",
"Bishop'S University",
"Blekinge Institute Of Technology",
"Bond University",
"Botswana Accountancy College",
"Bournemouth University",
"Bowen University",
"Bratislava International School Of Liberal Arts",
"British Columbia Institute Of Technology",
"Brno University Of Technology",
"Brock University",
"Buckinghamshire New University",
"Budapest University Of Technology And Economics",
"Bugema University",
"Busoga University",
"Cairo University",
"Canadian Mennonite University",
"Canterbury Christ Church University",
"Cape Peninsula University Of Technology",
"Capital University Of Economics And Business",
"Cardiff Metropolitan University",
"Cardinal Stefan Wyszynski University In Warsaw",
"Carleton University",
"Carol Davila University Of Medicine And Pharmacy",
"Catholic University In Ruzomberok",
"Catholic University Of Eastern Africa",
"Catholic University Of Leuven",
"Catholic University Of The Sacred Heart",
"Central European University",
"Central South University Of Forestry And Technology",
"Central University Of Finance And Economics",
"Central University Of Gujarat",
"Central University Of Rajasthan",
"Charles University",
"Chelyabinsk State University",
"Chernivtsi National University",
"China Agricultural University",
"China Foreign Affairs University",
"China University Of Geosciences",
"China University Of Political Science And Law",
"Chinhoyi University Of Technology",
"Chongqing University",
"Chubu University",
"Chulalongkorn University",
"Cihan University",
"City University Of Hong Kong",
"Cochin University Of Science And Technology",
"College Of Europe",
"Communication University Of China",
"Copenhagen University",
"Corvinus University Of Budapest",
"Covenant University",
"Coventry University",
"Cracow University Of Economics",
"Cranfield University",
"Daegu University",
"Dalhousie University",
"Dalian Maritime University",
"Damascus University",
"Darul Ihsan University",
"Daystar University",
"De Montfort University",
"Deakin University",
"Democritus University Of Thrace",
"Dokkyo University",
"Dongbei University Of Finance And Economics",
"Donghua University",
"Dublin City University",
"Durban University Of Technology",
"East China Normal University",
"East China University Of Science And Technology",
"Eastern Mediterranean University",
"Edinburgh Napier University",
"Enugu State University Of Science And Technology",
"Estonian Business School",
"Ethiopian Civil Service University",
"European Humanities University",
"European University",
"European University Cyprus",
"European University Institute",
"European University Of Lefke",
"Ewha Womans University",
"Falmouth University",
"Fatima Jinnah Women University",
"Federal University Of Technology Akure",
"Financial University Under The Government Of The Russian Federation",
"Foreign Trade University",
"Free International University Of Moldova",
"Free University Of Tbilisi",
"Fudan University",
"Galatasaray University",
"Gauhati University",
"Georgian Technical University",
"German Jordanian University",
"Ghana Institute Of Management And Public Administration (Gimpa)",
"Ghent University",
"Ghulam Ishaq Khan Institute Of Engineering Sciences And Technology",
"Girne American University",
"Goldsmiths, University Of London",
"Government College University Lahore",
"Griffith University",
"Guangdong University Of Foreign Studies",
"Gujarat Technological University",
"Gujarat University",
"Gulu University",
"Guru Gobind Singh Indraprastha University",
"Guru Jambheshwar University Of Science And Technology",
"Haigazian University",
"Hamdard University",
"Hanken School Of Economics",
"Hannam University",
"Harbin Institute Of Technology",
"Hasselt University",
"Hawassa University",
"Hebei Normal University",
"Heilongjiang University",
"Higher School Of Economics",
"Himachal Pradesh University",
"Hitotsubashi University",
"Hong Kong Baptist University",
"Hong Kong University Of Science And Technology",
"Hope Africa University",
"Huazhong University Of Science And Technology",
"Hunan University",
"Ie University",
"Imam Sadiq University",
"Imo State University",
"Indian Institute Of Science",
"Indian Institute Of Technology Guwahati",
"Indian Institute Of Technology, Delhi",
"Indian Statistical Institute",
"Institute Of Public Administration",
"International Christian University",
"International Institute For Population Sciences",
"International Islamic University Chittagong",
"International Islamic University Malaysia",
"International People'S College",
"International University In Geneva",
"International University Of Japan",
"International University Of Kyrgyzstan",
"International University Of Sarajevo",
"Iqra University",
"Iran University Of Science And Technology",
"Islamia University Of Bahawalpur",
"Islamic University In Uganda",
"Islamic University Of Gaza",
"Istanbul Technical University",
"Istanbul University",
"Ivan Franko National University Of Lviv",
"Ivane Javakhishvili Tbilisi State University",
"Ivano-Frankivsk National Technical University Of Oil And Gas",
"Jacobs University Bremen",
"Jadavpur University",
"Jagiellonian University",
"James Cook University",
"Jawaharlal Nehru Centre For Advanced Scientific Research",
"Jerusalem University College",
"Jiangsu University",
"Jiangxi University Of Finance And Economics",
"Jilin University",
"Jimma University",
"Jinan University",
"Jomo Kenyatta University Of Agriculture And Technology",
"Jones International University",
"Jordan University Of Science And Technology",
"Kdi School Of Public Policy And Management",
"Kabul University",
"Kalashnikov Izhevsk State Technical University",
"Kaliningrad State Technical University",
"Kampala International University",
"Kaplan University",
"Karadeniz Technical University",
"Karakoram International University",
"Kathmandu University",
"Kaunas University Of Technology",
"Kazan Federal University",
"Keele University",
"Kenyatta University",
"Kharkiv National University Of Economics",
"Khazar University",
"Kherson State University",
"King Abdulaziz University",
"King Abdullah University Of Science And Technology",
"King'S University College",
"Kingston University",
"Klaipeda University",
"Koc University",
"Kocaeli University",
"Korea University",
"Kuban State University",
"Kwame Nkrumah University Of Science And Technology",
"Kyambogo University",
"Kyoto University",
"Kyrgyz Russian Slavic University",
"Kyungwon University",
"L.N. Gumilyov Eurasian National University",
"Lagos State University",
"Lahore College For Women University",
"Lakehead University",
"Lancaster University",
"Lanzhou University",
"Laval University",
"Liaoning Normal University",
"Lingnan University",
"Linnaeus University",
"Liverpool John Moores University",
"London Business School",
"London Metropolitan University",
"London School Of Economics And Political Science",
"London South Bank University",
"Loughborough University",
"Lund University",
"Lviv Polytechnic National University",
"Lyceum Of The Philippines University",
"Maastricht University",
"Macquarie University",
"Magadh University",
"Maharshi Dayanand University",
"Mahatma Gandhi University",
"Marmara University",
"Masaryk University",
"Masinde Muliro University Of Science And Technology",
"Massey University",
"Maulana Azad National Institute Of Technology",
"Mbarara University Of Science And Technology",
"Mcgill University",
"Mcmaster University",
"Memorial University Of Newfoundland",
"Mendel University In Brno",
"Michael Okpara University Of Agriculture",
"Middle East Technical University",
"Midlands State University",
"Mindanao State University - Iligan Institute Of Technology",
"Ming Chuan University",
"Minia University",
"Minsk State Linguistic University",
"Misr University For Science And Technology",
"Mogadishu University",
"Moldova State University",
"Mongolian State University Of Education",
"Mongolian University Of Science And Technology",
"Moscow Engineering Physics Institute",
"Moscow Polytechnic University",
"Moscow State Institute Of International Relations",
"Moscow State Pedagogical University",
"Moscow State University",
"Mount Allison University",
"Mount Meru University",
"Mount Saint Vincent University",
"Ned University Of Engineering And Technology",
"Nagoya University",
"Nanjing Normal University",
"Nanjing University",
"Nankai University",
"Nanyang Technological University",
"National Aviation University",
"National Cheng Kung University",
"National Chengchi University",
"National Chung Hsing University",
"National Dong Hwa University",
"National Institute Of Technology, Rourkela",
"National Law School Of India University",
"National Metallurgical Academy Of Ukraine",
"National Open University Of Nigeria",
"National Taiwan Normal University",
"National Taiwan University",
"National Technical University Of Athens",
"National Transport University",
"National University Of Modern Languages",
"National University Of Ireland",
"National University Of Lesotho",
"National University Of Management",
"National University Of Mongolia",
"National University Of Singapore",
"National University Of Uzbekistan",
"Nazarbayev University",
"New Bulgarian University",
"New College Of California",
"New Era University",
"Nicolaus Copernicus University",
"Nigerian Defence Academy",
"Nirma University",
"Nkumba University",
"Nnamdi Azikiwe University",
"North South University",
"North-Eastern Hill University",
"North-West University",
"Northeast Normal University",
"Northern Caribbean University",
"Northumbria University",
"Northwest A&F University",
"Nottingham Trent University",
"Nova School Of Business And Economics",
"Novosibirsk State University",
"Obafemi Awolowo University",
"Ocean University Of China",
"Ochanomizu University",
"Oklahoma State University",
"Olabisi Onabanjo University",
"Oles Honchar Dnipro National University",
"Omdurman Ahlia University",
"Omsk State Technical University",
"Omsk State University",
"Open University Malaysia",
"Osmania University",
"Osun State University",
"Other",
"Oxford Brookes University",
"Psg College Of Technology",
"Pan-African University",
"Panjab University",
"Peking University",
"Penza State University",
"Petra Christian University",
"Philadelphia University",
"Philippine Christian University",
"Philippine Normal University",
"Pokhara University",
"Pondicherry University",
"Providence University",
"Puntland State University",
"Purbanchal University",
"Pusan National University",
"Pwani University",
"Queen'S University",
"Queen'S University Belfast",
"Rabindra Bharati University",
"Radboud University Nijmegen",
"Renmin University Of China",
"Rhodes University",
"Riga Stradins University",
"Ritsumeikan Asia Pacific University",
"Robert Gordon University",
"Romanian-American University",
"Rostov State University Of Economics",
"Royal College Of Art",
"Royal Military College Of Canada",
"Royal Roads University",
"Royal University Of Agriculture",
"Royal University Of Phnom Penh",
"Russian State Social University",
"Russian State University For The Humanities",
"Russian-Armenian University",
"Ryerson University",
"Saint Mary'S University",
"Saint Paul University",
"Saint Petersburg State University",
"Samara University",
"Sana'A University",
"Sanjay Gandhi Postgraduate Institute Of Medical Sciences",
"Sant Gadge Baba Amravati University",
"Saratov State Academy Of Law",
"Sardar Patel University",
"Semey State Medical University",
"Seoul National University",
"Seoul Women'S University",
"Shahed University",
"Shahid Bahonar University Of Kerman",
"Shandong University",
"Shanghai International Studies University",
"Shanghai Jiao Tong University",
"Shanghai Normal University",
"Shanghai University",
"Shanghai University Of Finance And Economics",
"Shanghai University Of International Business And Economics",
"Sharif University Of Technology",
"Sheffield Hallam University",
"Shimer College",
"Shiraz University",
"Sichuan University",
"Silliman University",
"Simon Fraser University",
"Singapore Management University",
"Sir Syed University Of Engineering And Technology",
"Sogang University",
"Solusi University",
"Soochow University",
"Sophia University",
"South Asian University",
"South China Agricultural University",
"South China University Of Technology",
"South East European University",
"Southern Cross University",
"Southwest University",
"Southwestern University Of Finance And Economics",
"St. Augustine University Of Tanzania",
"St. Francis Xavier University",
"St. George'S University",
"Staffordshire University",
"State University Of Management",
"Stockholm School Of Economics",
"Stockholm School Of Economics In Riga",
"Strathmore University",
"Strayer University",
"Sun Yat-Sen University",
"Swansea University",
"Swedish University Of Agricultural Sciences",
"Swinburne University Of Technology",
"Sylhet Agricultural University",
"Tajik National University",
"Tallinn University",
"Tambov State Technical University",
"Tampere University",
"Tansian University",
"Taras Shevchenko National University Of Kyiv",
"Tarbiat Modares University",
"Tata Institute Of Social Sciences",
"Tay Nguyen University",
"Technical University Of Denmark",
"Technical University Of Liberec",
"Technical University Of Mombasa",
"Technion - Israel Institute Of Technology",
"Tel Aviv University",
"The American University In Cairo",
"The Catholic University Of America",
"The Chinese University Of Hong Kong",
"The Maharaja Sayajirao University Of Baroda",
"The Open University",
"The University Of Adelaide",
"The University Of British Columbia",
"The University Of Edinburgh",
"The University Of Hong Kong",
"The University Of Manchester",
"The University Of Queensland",
"The University Of Sheffield",
"The University Of Winnipeg",
"Thompson Rivers University",
"Tianjin Medical University",
"Tianjin University",
"Tilburg University",
"Tishreen University",
"Tohoku University",
"Tomsk Polytechnic University",
"Tomsk State University",
"Tongji University",
"Toulouse School Of Economics",
"Trent University",
"Tribhuvan University",
"Trinity College Dublin",
"Trinity Western University",
"Tshwane University Of Technology",
"Tsinghua University",
"Tunghai University",
"Tyumen State University",
"Umea University",
"United Nations University",
"United States Military Academy",
"Universidad Finis Terrae",
"Universidad Iberoamericana",
"University College Cork",
"University College Dublin",
"University College London",
"University Of Balochistan",
"University Of Cape Coast",
"University Of Dar Es Salaam",
"University Of Jammu",
"University Of Patras",
"University Of Surrey",
"University Of Uyo",
"University Politehnica Of Bucharest",
"University For Development Studies",
"University Of Aberdeen",
"University Of Agder",
"University Of Alberta",
"University Of Amsterdam",
"University Of Antwerp",
"University Of Baghdad",
"University Of Banja Luka",
"University Of Basel",
"University Of Bath",
"University Of Bedfordshire",
"University Of Belgrade",
"University Of Benin",
"University Of Bergamo",
"University Of Bergen",
"University Of Birmingham",
"University Of Bolton",
"University Of Botswana",
"University Of Bradford",
"University Of Brighton",
"University Of Bristol",
"University Of Bucharest",
"University Of Calabria",
"University Of Calcutta",
"University Of Calgary",
"University Of Calicut",
"University Of California, Berkeley",
"University Of Cambridge",
"University Of Canberra",
"University Of Canterbury",
"University Of Cape Town",
"University Of Central Lancashire",
"University Of Chittagong",
"University Of Colombo",
"University Of Crete",
"University Of Delhi",
"University Of Derby",
"University Of Development Alternative",
"University Of Dhaka",
"University Of Divinity",
"University Of Dodoma",
"University Of Dundee",
"University Of East Anglia",
"University Of East London",
"University Of Eastern Africa, Baraton",
"University Of Eastern Finland",
"University Of Economics In Bratislava",
"University Of Education, Winneba",
"University Of Exeter",
"University Of Ferrara",
"University Of Florence",
"University Of Fort Hare",
"University Of Fribourg",
"University Of Geneva",
"University Of Genoa",
"University Of Ghana",
"University Of Glasgow",
"University Of Gloucestershire",
"University Of Gondar",
"University Of Greenwich",
"University Of Groningen",
"University Of Guelph",
"University Of Guilan",
"University Of Haifa",
"University Of Helsinki",
"University Of Hull",
"University Of Hyderabad",
"University Of Ibadan",
"University Of Iceland",
"University Of Ilorin",
"University Of Indonesia",
"University Of Insubria",
"University Of International Business And Economics",
"University Of Ioannina",
"University Of Isfahan",
"University Of Johannesburg",
"University Of Kalamoon",
"University Of Kalyani",
"University Of Karachi",
"University Of Kashmir",
"University Of Kerala",
"University Of Khartoum",
"University Of King'S College",
"University Of Kufa",
"University Of Kwazulu-Natal",
"University Of Latvia",
"University Of Lausanne",
"University Of Leeds",
"University Of Leicester",
"University Of Lethbridge",
"University Of Liberia",
"University Of Lincoln",
"University Of Liverpool",
"University Of Ljubljana",
"University Of Lodz",
"University Of London",
"University Of Lucknow",
"University Of Macedonia",
"University Of Madras",
"University Of Maiduguri",
"University Of Malakand",
"University Of Management & Technology",
"University Of Melbourne",
"University Of Milan",
"University Of Montenegro",
"University Of Moratuwa",
"University Of Mumbai",
"University Of Nairobi",
"University Of Namibia",
"University Of National And World Economy",
"University Of New Brunswick",
"University Of North Bengal",
"University Of Northampton",
"University Of Nottingham",
"University Of Novi Sad",
"University Of Oslo",
"University Of Otago",
"University Of Ottawa",
"University Of Oulu",
"University Of Oxford",
"University Of Padua",
"University Of Palestine",
"University Of Parma",
"University Of Peloponnese",
"University Of Peradeniya",
"University Of Perugia",
"University Of Peshawar",
"University Of Petra",
"University Of Piraeus",
"University Of Pisa",
"University Of Plymouth",
"University Of Port Harcourt",
"University Of Portsmouth",
"University Of Pretoria",
"University Of Rajasthan",
"University Of Rajshahi",
"University Of Reading",
"University Of Regina",
"University Of Ruhuna",
"University Of Rwanda",
"University Of Salerno",
"University Of Salford",
"University Of Santo Tomas",
"University Of Sargodha",
"University Of Saskatchewan",
"University Of Sassari",
"University Of Science And Technology",
"University Of Science And Technology Of China",
"University Of Science, Malaysia",
"University Of Shanghai For Science And Technology",
"University Of Sierra Leone",
"University Of Silesia In Katowice",
"University Of Sindh",
"University Of South Africa",
"University Of South Australia",
"University Of South Wales",
"University Of Southampton",
"University Of Southeastern Philippines",
"University Of Southern Denmark",
"University Of Southern Queensland",
"University Of Sri Jayewardenepura",
"University Of St. Cyril And Methodius In Trnava",
"University Of St. Gallen",
"University Of Stirling",
"University Of Strathclyde",
"University Of Sulaimani",
"University Of Sunderland",
"University Of Sussex",
"University Of Tabriz",
"University Of Tartu",
"University Of Tasmania",
"University Of Technology Sydney",
"University Of Tehran",
"University Of Teramo",
"University Of The Gambia",
"University Of Thessaly",
"University Of Tirana",
"University Of Trento",
"University Of Tsukuba",
"University Of Turin",
"University Of Turku",
"University Of Vaasa",
"University Of Verona",
"University Of Victoria",
"University Of Virginia",
"University Of Waikato",
"University Of Wales",
"University Of Warsaw",
"University Of Warwick",
"University Of Washington",
"University Of Waterloo",
"University Of West London",
"University Of Winchester",
"University Of Windsor",
"University Of Wolverhampton",
"University Of World Economy And Diplomacy",
"University Of York",
"University Of Zagreb",
"University Of Zimbabwe",
"University Of Zululand",
"University Of The Free State",
"University Of The Philippines Diliman",
"University Of The Philippines Open University",
"University Of The Philippines Visayas",
"University Of The Punjab",
"University Of The Western Cape",
"University Of The Witwatersrand, Johannesburg",
"Ural Federal University",
"Usmanu Danfodiyo University Sokoto",
"Utkal University",
"Utrecht University",
"Uzhhorod National University",
"V.N. Karazin Kharkiv National University",
"Valley View University",
"Vellore Institute Of Technology",
"Victoria University Of Wellington",
"Volgograd State University",
"Voronezh State University",
"Vyatka State University",
"Walter Sisulu University",
"Warsaw School Of Economics",
"Warsaw University Of Technology",
"Waseda University",
"Wawasan Open University",
"Webster University Geneva",
"Western University",
"Westminster International University In Tashkent",
"Westwood College",
"Wilfrid Laurier University",
"William Mitchell College Of Law",
"Wuhan University",
"Wuhan University Of Technology",
"Xi'An Jiaotong University",
"Xi'An Jiaotong-Liverpool University",
"Xiamen University",
"Xidian University",
"Yalova University",
"Yanshan University",
"Yarmouk University",
"Yeditepe University",
"Yerevan State University",
"Yokohama National University",
"Yonsei University",
"York University",
"Zagazig University",
"Zhejiang Normal University",
"Zhejiang University",
"Zhengzhou University",
"Zhongnan University Of Economics And Law",
"Zimbabwe Open University",
"Aarhus Technical College",
"Agricultural University Of Georgia",
"Al-Azhar University",
"Aria Institute Of Higher Education",
"Atma Jaya Catholic University Of Indonesia",
"Bahcesehir University",
"Baikal National University Of Economics And Law",
"Bashkir State Medical University",
"Beijing University Of Science And Technology",
"Bloomfield College",
"Bridgewater College",
"Brooks Institute Of Photography",
"Cardiff University",
"Catholic University Of Leuven",
"Charles Sturt University",
"Chengdu University Of Technology",
"Christ University",
"Chung-Ang University",
"Chuvash State University",
"City University Of New York, Brooklyn College",
"City University Of New York, Hunter College",
"City University Of New York, Lehman College",
"College Of New Rochelle",
"Comenius University In Bratislava",
"Copenhagen Business School",
"Davis And Elkins College",
"Don State Technical University",
"Dublin Institute Of Technology",
"East Kazakhstan State University",
"Eotvos Lorand University",
"Estonian Academy Of Arts",
"Ethiopian Civil Service University",
"European Business School",
"Fakir Mohan University",
"Fatih University",
"German University In Cairo",
"Goa University",
"Goucher College",
"Green Mountain College",
"Guangdong University Of Finances And Economics",
"Hacettepe University",
"Hanover College",
"Hasanuddin University",
"Helsinki University Of Technology",
"Henan Normal University",
"Herat University",
"Hertie School Of Governance",
"Huazhong Agricultural University",
"Humber College",
"I.M. Sechenov First Moscow State Medical University",
"Indian Institute Of Technology, Indore",
"Indonesia University Of Education",
"Institute Of Social Studies",
"Institute Of Transpersonal Psychology",
"Interdisciplinary Center Herzliya",
"Jilin Normal University",
"Kabul Education University",
"Knoxville College",
"Korea Advanced Institute Of Science And Technology",
"Ladoke Akintola University Of Technology",
"Lock Haven University Of Pennsylvania",
"Mahidol University",
"Moscow Institute Of Physics And Technology",
"Murmansk State Technical University",
"National Aviation Academy",
"National Institute Of Technology, Calicut",
"National University Of Malaysia",
"Near East University",
"New Economic School",
"North Ossetian State University",
"Northeast Agricultural University",
"Northwestern College Iowa",
"Norwegian University Of Science And Technology",
"Novosibirsk State Technical University",
"Open University Of Tanzania",
"Opole University Of Technology",
"Palm Beach State College",
"Payame Noor University",
"Perm State University",
"Plekhanov Russian Academy Of Economics",
"Plekhanov Russian University Of Economics",
"Polytechnic University",
"Preston University",
"Queensland University Of Technology",
"Roanoke College",
"Royal University Of Law And Economics",
"Samara State University Of Economics",
"School Of Finance And Banking",
"Shanghai University Of Sport",
"Shantou University",
"Sherbrooke University",
"Siberian Federal University",
"Sichuan Fine Art Institute",
"Southern California College",
"Southern Ural State University",
"St. John Fisher College",
"St. Petersburg State Conservatory",
"St. Thomas University",
"State University Of Tetova",
"Swiss Federal Institute Of Technology",
"Swiss Federal Institute Of Technology, Zurich",
"Tashkent State Technical University",
"Tashkent State University Of Economics",
"Ternopil Academy Of National Economy",
"The American College",
"The University Of Hong Kong",
"Trinity Theological Seminary",
"Ukhta State Technical University",
"Ukrainian Academy Of Banking",
"University For Peace",
"University Of Applied Sciences",
"University Of Bologna",
"University Of Cagliari",
"University Of California, San Francisco",
"University Of Cyprus",
"University Of Debrecen",
"University Of International Business And Economics",
"University Of Lagos",
"University Of Limpopo",
"University Of Macerata",
"University Of Malaya",
"University Of Malaysia, Perlis",
"University Of Malta",
"University Of Manitoba",
"University Of Messina",
"University Of Miskolc",
"University Of Mississippi Medical Center",
"University Of Miyazaki",
"University Of Mosul",
"University Of New South Wales",
"University Of Nigeria",
"University Of Palermo",
"University Of Pannonia",
"University Of Presov",
"University Of Pune",
"University Of Rijeka",
"University Of San Carlos",
"University Of Siena",
"University Of Split",
"University Of Stellenbosch",
"University Of Tartu",
"University Of The Arts",
"University Of The City Of Manila",
"University Of Trieste",
"University Of Venice",
"University Of Wales, Swansea",
"University Of Westminster",
"Vasyl Stefanyk Precarpathian National University",
"Walsh University",
"Waynesburg College",
"Wesleyan College",
"Whittier College",
"Yaba College Of Technology",
"Yildiz Technical University",
"Zagreb School Of Economics And Management",
"Zhejiang University Of Technology"
   ];
   
    $("[fs-field-validation-name='1.2 University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
  
  $("[fs-field-validation-name='2.1.2) University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
  
  $("[fs-field-validation-name='3.1.2) University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
  
  } );
