$( function() {
    var availableTags = [
      "A T Still University-Health",
"AIU Online",
"ASA College",
"Abilene Christian University",
"Abraham Baldwin Agricultural College",
"Accent Reduction Training Association - Atlanta",
"Acton School of Business",
"Adams State University",
"Admissions Office - Chattahoochee Technical College",
"Adrian College",
"Agnes Scott College",
"Alabama A&M University",
"Alabama State University",
"Alaska Career College",
"Alaska Pacific University",
"Albany College of Pharmacy and Health Sciences",
"Albany Law School",
"Albany State University",
"Albert Einstein College of Medicine",
"Albertus Magnus College",
"Albion College",
"Albizu University",
"Albright College",
"Alderson Broaddus University",
"Alexandria Technical & Community College",
"Alfred University",
"Alice Lloyd College",
"Allan Hancock College",
"Allegany College of Maryland",
"Allen Community College",
"Alliant International University",
"Allied Institute of Professional Studies",
"Amarillo College - Russell Hall",
"American Academy of Art College",
"American Film Institute",
"American Friends of The Hebrew University",
"American International College",
"American River College",
"Amherst College",
"Anderson University",
"Andrew Jackson Language Academy",
"Andrews University",
"Angelina College",
"Angelo State University",
"Anne Arundel Community College",
"Anschutz",
"Antelope Valley College",
"Antioch University Midwest",
"Antioch University New England",
"Antioch University Seattle",
"Antonin Scalia Law School",
"Appalachian State University",
"Appomattox Regional Governor's School",
"Aquinas College",
"Arapahoe Community College",
"Arcadia University",
"Archbishop Spalding High School",
"Argosy University Seattle",
"Argosy University, Chicago",
"Argosy University, Dallas",
"Argosy University, Orange County",
"Argosy University, Phoenix",
"Argosy University, Sarasota",
"Argosy University, Twin Cities",
"Arizona Christian University",
"Arizona State University Polytechnic Campus",
"Arizona Summit Law School",
"Arizona Western College",
"Arkansas State University",
"Arkansas Tech University",
"Art Academy of Cincinnati",
"ArtCenter College of Design",
"Asbury Theological Seminary",
"Asbury University",
"Asheville-Buncombe Technical Community College",
"Ashland University",
"Ashworth College",
"Athens State University",
"Atlanta Broadcast Institute",
"Atlanta Metropolitan State College",
"Atlantic Cape Community College",
"Atlantic International University",
"Auburn University",
"Auburn University at Montgomery",
"Augsburg University",
"Augusta University - Summerville Campus",
"Aurora University",
"Austin College and Career Academy High School",
"Austin Peay State University",
"Ave Maria School of Law",
"Ave Maria University",
"Averett University",
"Avila University",
"Azusa Pacific University",
"Babson College",
"Bacone College",
"Baker College of Jackson",
"Bakersfield College",
"Baldwin Wallace University",
"Ball State University",
"Baptist College of Ministry",
"Baptist University of the Americas",
"Barclay College",
"Bard College",
"Bard College at Simon's Rock",
"Barrett, The Honors College at Arizona State University",
"Barton College",
"Baruch College",
"Bates College",
"Baton Rouge Community College",
"Bay College",
"Bay College West Campus",
"Bay Path University",
"Baylor University",
"Becker Friedman Institute for Research in Economics",
"Belhaven University",
"Bellarmine University",
"Bellevue College",
"Bellevue University",
"Belmont Abbey",
"Beloit College",
"Benedict College",
"Benedictine Ravens",
"Benjamin Franklin Institute of Technology (BFIT)",
"Bennett College",
"Bentley University",
"Berea College",
"Bergen Community College",
"Berkeley City College",
"Berkeley Law",
"Berkeley School of Theology",
"Berkshire Community College",
"Bethany College",
"Bethany Lutheran College",
"Bethel College",
"Bethel University",
"Bethlehem College & Seminary",
"Bethune-Cookman University",
"Binghamton University",
"Biola University",
"Birmingham-Southern College",
"Bismarck State College",
"Black Hawk College East Campus",
"Black Hills State University",
"Blackburn College",
"Blanche Ely High School",
"Bloomsburg University of Pennsylvania",
"Blue Heron Academy",
"Blue Ridge Job Corps Center",
"Bluefield College",
"Bluefield State College",
"Bluegrass Community & Technical College",
"Bluffton University",
"Boerigter Center for Calling and Career",
"Boise State University",
"Borough of Manhattan Community College",
"Boston College",
"Boston Institute of Finance",
"Boston University",
"Boston University Fenway Campus",
"Bowie State University",
"Bowling Green State University",
"Bradley University",
"Brandeis University",
"Brenau University",
"Brescia University",
"Bridgewater College",
"Brigham Young University",
"Brigham Young University-Idaho",
"Brigham Young University–Hawaii",
"Brite Divinity School",
"Bronx Community College",
"Brookdale Community College",
"Brooklyn College",
"Brooklyn Law School",
"Broward College-Weston | Administrative Center",
"Brown University",
"Bryant University",
"Bryant and Stratton Business College",
"Bryn Athyn College",
"Bucknell University",
"Bunker Hill Community College",
"Butler County Community College (BC3 Main Campus)",
"Butler University",
"Butte College",
"CCM",
"CNM Main Campus Student Services Center (SSC)",
"CRAS - Conservatory of Recording Arts and Sciences",
"CSB Media Arts Center",
"CUNY College of Staten Island",
"CUNY Graduate Center",
"Cabell County Career Technology Center",
"Cabrillo College",
"Cal Poly Pomona",
"Caldwell Community College and Technical Institute",
"Calhoun Community College",
"California Coast University",
"California College of the Arts",
"California Institute of Integral Studies",
"California Institute of Technology",
"California Institute of the Arts",
"California Lutheran University",
"California Polytechnic State University",
"California State University Channel Islands",
"California State University Long Beach",
"California State University San Marcos",
"California State University, Bakersfield",
"California State University, Dominguez Hills",
"California State University, East Bay",
"California State University, Fresno",
"California State University, Fullerton",
"California State University, Los Angeles",
"California State University, Monterey Bay",
"California State University, Northridge",
"California State University, Sacramento",
"California State University, San Bernardino",
"California State University, Stanislaus",
"California University of Pennsylvania",
"California Western School of Law",
"Calumet College of St. Joseph",
"Calvary Christian School",
"Calvin Theological Seminary",
"Calvin University",
"Cambridge College",
"Camden County College",
"Campbell University",
"Campbellsville University",
"Canisius College",
"Cape Cod Community College Bookstore",
"Capella University",
"Capital University",
"Cardinal Stritch University",
"Cardozo School of Law",
"Carl Albert State College",
"Carl Sandburg College",
"Carleton College",
"Carlow University",
"Carlson School of Management",
"Carnegie Mellon University",
"Carroll University",
"Carson-Newman University",
"Carver Center for Arts and Technology",
"Cascadia College",
"Case Western Reserve University",
"Case Western Reserve University School of Law Office of Admissions",
"Castleton University",
"Catawba Valley Community College",
"Catholic Theological Union",
"Cayuga Community College",
"Cazenovia College",
"Cañada College",
"Cedar Crest College",
"Cedarville University",
"Centenary College of Louisiana",
"Center For Bioethics",
"Center For California Studies",
"Central Baptist College",
"Central Bible College",
"Central College",
"Central Community College - Grand Island",
"Central Connecticut State University",
"Central Maine Community College",
"Central Methodist University",
"Central Ohio Technical College",
"Central Oregon Community College",
"Central Penn College",
"Central Piedmont Community College",
"Central School of Practical Nursing",
"Central State University",
"Central University of Rajasthan",
"Central Virginia Community College",
"Central Washington University",
"Central Wyoming College",
"Centre College",
"Century College",
"Cerritos College",
"Chabot College",
"Chamberlain University",
"Chaminade University of Honolulu",
"Champlain College",
"Chandler Gilbert Community College - Pecos Campus",
"Chapman University",
"Charleston School of Law",
"Charleston Southern University",
"Charter Oak State College",
"Chatham University",
"Chattanooga State Community College",
"Chemeketa Community College",
"Chesapeake Bay Governors School",
"Chesapeake College",
"Cheyney University Of Pennsylvania",
"Chicago Photography Academy",
"Chicago State University",
"Chowan University",
"Christendom College",
"Christian Brothers University",
"Christopher Newport University",
"Cincinnati Christian University",
"Cincinnati State Technical and Community College",
"Citrus College",
"City College of San Francisco",
"City University of New York",
"Clackamas Community College",
"Claflin University",
"Claremont Graduate University",
"Claremont McKenna College",
"Clarion University",
"Clark Atlanta University",
"Clark College",
"Clark State College, Springfield",
"Clark University",
"Clarke University",
"Clarkson University",
"Clayton State University",
"Clearwater Christian College",
"Cleary University",
"Clemson Alumni Association",
"Clemson University",
"Cleveland State Community College",
"Cleveland State University",
"Clovis Community College",
"Coahoma Community College",
"Coastal Alabama Community College",
"Coastal Carolina University",
"Coastline College",
"Cochise College Sierra Vista Campus",
"Coe College",
"Coffeyville Community College",
"Coker University",
"Colby College",
"Colby-Sawyer College",
"Colgate University",
"College For Creative Studies",
"College Union Building",
"College of Biblical Studies",
"College of Central Florida Ocala Campus",
"College of Dupage",
"College of Humanities and Social Sciences",
"College of Idaho",
"College of Lake County",
"College of Law - Syracuse University",
"College of Marin",
"College of Mount Saint Vincent",
"College of Our Lady of the Elms",
"College of Southern Idaho",
"College of Southern Maryland",
"College of Southern Nevada (South)",
"College of Southern Nevada Charleston Campus",
"College of the Canyons",
"College of the Desert",
"College of the Holy Cross",
"College of the Ozarks",
"College of the Redwoods",
"College of the Sequoias",
"College of the Siskiyous",
"Collin College",
"Colorado Christian University",
"Colorado College",
"Colorado Mesa University",
"Colorado School of Mines",
"Colorado State University",
"Colorado State University Pueblo",
"Colorado Technical University",
"Columbia Business School",
"Columbia College",
"Columbia College Chicago",
"Columbia Law School",
"Columbia University",
"Columbus Alternative High School",
"Columbus State Community College",
"Columbus State University",
"Community College of Aurora - Lowry Campus",
"Community College of Beaver County",
"Community College of Philadelphia - Main Campus",
"Community College of Vermont (CCV) - Winooski",
"Community College of the Air Force",
"Concordia Theological Seminary",
"Concordia University",
"Concordia University Chicago",
"Concordia University Irvine",
"Concordia University Texas",
"Concordia University Wisconsin",
"Concordia University, Nebraska",
"Conviser Law Center at Illinois Institute of Technology",
"Copiah-Lincoln Community College",
"Copper Mountain College",
"Coppin State University",
"Cornell College",
"Cornell University",
"Cornerstone University",
"Cottey College",
"Covenant College",
"Cowley College",
"Creighton Bluejays",
"Crown College",
"Cuesta College",
"Curtin University",
"Curtis Institute of Music",
"Cypress College",
"Dakota County Technical College",
"Dakota Ridge High School",
"Dakota State University",
"Dakota Wesleyan University",
"Dallas Baptist University",
"Dallas College Brookhaven Campus",
"Dallas College Cedar Valley Campus",
"Dallas College El Centro Campus",
"Dallas College Mountain View Campus",
"Dallas College North Lake Campus",
"Dallas College Richland Campus",
"Dalton State College",
"Dana College",
"Darden School of Business - University of Virginia",
"Dartmouth College",
"Davenport University",
"Davidson College",
"Davis & Elkins College",
"Davis Technical College",
"Daytona State College",
"De Anza College",
"DePaul Blue Demons",
"DePauw Tigers",
"DeVry University",
"Dean College",
"Defense Language Institute Foreign Language Center",
"Del Mar College",
"Delaware College of Art and Design (DCAD)",
"Delaware County Community College",
"Delaware Valley University",
"Delgado Community College",
"Delta College",
"Delta State University",
"Denison University",
"Denver Seminary",
"Department of Economics",
"Dickinson College",
"Divine Word Seminary",
"Dixie State University",
"Doane University",
"Dodge City Community College",
"Dominican School of Philosophy & Theology",
"Dominican University",
"Don Bosco Technical Institute",
"Dordt University",
"Dowling College",
"Downey Court Reporting",
"Drake University",
"Drew University",
"Drexel University",
"Drury University",
"Dubuque Senior High School",
"Duke University Sanford School of Public Policy",
"Duke University School of Law",
"Dunlap-Mathis Building",
"Duquesne University",
"Dutchess Community College",
"Eagle Global Advisors",
"Earlham College",
"East Carolina University",
"East Central College",
"East Los Angeles College",
"East Tennessee State University",
"East Texas Baptist University",
"Eastern Connecticut State University",
"Eastern Florida State College",
"Eastern Illinois University",
"Eastern Kentucky University",
"Eastern Maine Community College",
"Eastern Mennonite University",
"Eastern Michigan University",
"Eastern New Mexico University",
"Eastern Oregon University",
"Eastern University",
"Eastern Washington University",
"Eastman School of Music",
"Eckerd College",
"Edison State Community College",
"Edith Cowan University Joondalup Campus",
"Edmonds College",
"Eindhoven University of Technology",
"Eindhoven University of Technology (Technische Universiteit Eindhoven)",
"El Camino College",
"Elgin Community College",
"Elizabeth City State University",
"Elizabethtown College",
"Ellis University",
"Elmhurst University",
"Elon University",
"Emerson College",
"Emory & Henry College",
"Emory University",
"Emory University School of Law",
"Emporia State University",
"Endicott College",
"English Language Learning and World Languages Department at Harold Washington College",
"Erasmus University Rotterdam",
"Erskine College",
"Essex County College",
"Estrella Mountain Community College",
"Eugene Lang College of Liberal Arts at The New School",
"Eugene O'Neill Theater Center",
"Eureka College",
"Evangel University",
"Everest University",
"Everett Community College",
"Excelsior College",
"FIDM/Fashion Institute of Design & Merchandising",
"Fairfield University",
"Fairleigh Dickinson University",
"Fairmont State University",
"Faith Bible Seminary",
"Faith International University & Seminary",
"Fashion Institute of Technology",
"Faulkner University",
"Fayetteville State University",
"Felician University",
"Fernandina Beach High School",
"Ferris State University",
"Fielding Graduate University",
"Finger Lakes Community College",
"Fisk University",
"Fitchburg State University",
"Flashpoint Chicago, a Campus of Columbia College Hollywood",
"Florida A&M University",
"Florida Atlantic University",
"Florida Coastal School Of Law",
"Florida Gateway College",
"Florida Gulf Coast University",
"Florida Polytechnic University",
"Florida SouthWestern State College",
"Florida Southern College",
"Florida State College at Jacksonville – Downtown Campus",
"Florida State University",
"Folsom Lake College",
"Fontbonne University",
"Foothill College",
"Fordham University",
"Forsyth Technical Community College Main Campus",
"Fort Hays State University",
"Fort Lewis College",
"Fort Valley State University",
"Fox Valley Technical College",
"Framingham State University",
"Francis Marion University",
"Franciscan University of Steubenville",
"Franklin & Marshall College",
"Franklin Pierce University",
"Franklin University",
"Frederick Community College",
"Freed-Hardeman University",
"Fresno City College",
"Fresno Pacific University",
"Friends University",
"Front Range Community College",
"Frontier Nursing University",
"Full Sail University",
"Fuller Theological Seminary",
"Gadsden State Community College - Wallace Drive Campus",
"Gardner-Webb University",
"Garrett College",
"Garrett-Evangelical Theological Seminary",
"Gaston College",
"Gateway Seminary in Phoenix, Arizona",
"Geneva College",
"George Fox University: Newberg Campus",
"George Mason University",
"George Mason University School of Business - Fairfax Campus",
"George Wythe College",
"Georgia College",
"Georgia Gwinnett College",
"Georgia Highlands College",
"Georgia Institute of Technology",
"Georgia Southern University",
"Georgia Southern University Armstrong Campus",
"Georgia Southwestern State University",
"Georgia State University",
"Georgian Court University Bookstore",
"Gibson, Dunn & Crutcher LLP",
"Gideon Chang: The Life University (Free Online Classes)",
"Gilman School",
"Glenville State College",
"Global Information Technology",
"Globe Institute Of Technology",
"Gogebic Community College",
"Golden West College",
"Gonzaga University",
"Gordon College",
"Gordon State College",
"Goucher College",
"Governors State University",
"Grace College",
"Graceland University",
"Graduate School of Social Service",
"Graduate Theological Union",
"Grambling State University",
"Grand Valley State University",
"Gray Institute",
"Great Bay Community College",
"Green Mountain College",
"Green River College",
"Greenfield Community College",
"Greensboro College",
"Greenville Technical College",
"Grossmont College",
"Guilford College",
"Guilford Technical Community College",
"Gulf Coast State College",
"Gwynedd Mercy University",
"Halifax Community College",
"Hamilton College",
"Hampden-Sydney College",
"Hannibal-LaGrange University",
"Hardin-Simmons University",
"Harding University",
"Harford Community College",
"Harold Washington College, City College of Chicago",
"Harper College",
"Harrisburg Area Community College",
"Harry S Truman College",
"Hartnell College",
"Harvard Business School",
"Harvard College",
"Harvard Divinity School",
"Harvard Kennedy School",
"Harvard Law School",
"Hastings College",
"Haverford College",
"Hawaiʻi Pacific University",
"Hawkeye Community College Main Campus",
"Heartland Community College",
"Henderson State University",
"Hendrix College",
"Henry Clay High School",
"High Point University",
"Highline College",
"Hillsborough Community College - Plant City Campus",
"Hillsdale College",
"Hinds Community College - Raymond Campus",
"Hobart and William Smith Colleges",
"Hofstra University",
"Hollins University",
"Holmes Jr. College is Holmes Community College",
"Holy Cross College",
"Holy Names University",
"Holyoke Community College",
"Hood College",
"Hope College",
"Hope International University (HIU)",
"Housatonic Community College",
"Houston Baptist University",
"Houston Community College - Northeast Campus",
"Houston Community College - Spring Branch Campus",
"Howard College",
"Howard Community College",
"Howard Payne University",
"Hudson County Community College",
"Hudson Valley Community College",
"Humanitarian Disaster Institute",
"Humboldt State University",
"Hunter College",
"Huntington University",
"Huston-Tillotson University",
"Hutchinson Community College",
"IIT Institute of Design",
"IPR - College of Creative Arts",
"ITT Technical Institute - San Bernardino Campus",
"IUPUC",
"IUPUI",
"Illinois Institute of Technology",
"Illinois Media School",
"Illinois State University",
"Illinois Valley Community College",
"Indian River State College",
"Indiana Tech",
"Indiana University Bloomington",
"Indiana University South Bend",
"Indiana University Southeast",
"Indiana University of Pennsylvania",
"Indiana Wesleyan University - Merrillville Education and Conference Center",
"Institute for Training and Development, Inc.",
"Institute of American Indian Arts (IAIA)",
"IntelliTec College in Colorado Springs",
"Interdenominational Theological Center (ITC)",
"International Academy-Design",
"International School of Management",
"Inver Hills Community College",
"Iona College",
"Iowa Central Community College",
"Iowa State University",
"Irvine Valley College",
"Itawamba Community College",
"Ithaca College",
"Ivy Tech Community College",
"Jackson College",
"Jackson State University",
"Jacksonville State University",
"Jacksonville University",
"Jefferson Community and Technical College",
"Jefferson State Community College",
"John Brown University",
"John Carroll University",
"John F. Kennedy University",
"John Tyler Community College",
"Johns Hopkins Bloomberg School of Public Health",
"Johns Hopkins University",
"Johnson & Wales University Providence Campus",
"Johnson & Wales University- Charlotte Campus",
"Johnson C. Smith University",
"Johnson County Community College",
"Johnston Community College",
"Josef Korbel School of International Studies",
"Judson University",
"June Buchanan School",
"Juniata College",
"Kalamazoo College",
"Kalamazoo Valley Community College",
"Kansas City Kansas Community College",
"Kansas State University",
"Kansas Wesleyan University",
"Kapiʻolani Community College",
"Kauaʻi Community College",
"Kean University",
"Keiser University",
"Kennedy-King College",
"Kennesaw State University - Marietta Campus",
"Kent State University",
"Kentucky Christian University",
"Kentucky Wesleyan College",
"Kenyon College",
"Kettering University",
"Keuka College",
"Keystone College",
"Kilgore College",
"Kingman High School",
"Kingsborough Community College",
"Kirkwood Community College",
"Kishwaukee College",
"Knox College",
"Knox Theological Seminary",
"Knoxville College",
"Kutztown University of Pennsylvania",
"LIU Post",
"LONG BEACH CITY COLLEGE",
"La Roche University",
"La Salle Language Academy",
"La Salle University",
"Lahainaluna High School",
"Lake Michigan College",
"Lake Ridge Academy",
"Lake Superior College",
"Lake Superior State University",
"Lake Tahoe Community College",
"Lakeland Community College",
"Lakeland University - Sheboygan Center",
"Lakes Region Community College",
"Lamar University",
"Lancaster Bible College | Capital Seminary & Graduate School",
"Lane College",
"Lane Community College",
"Laney College",
"Lansing Community College",
"Laramie County Community College",
"Lasell University",
"Le Moyne College",
"LeMoyne-Owen College",
"Lee College",
"Leeward Community College",
"Lehigh Carbon Community College",
"Lehigh University",
"Lehigh Valley College",
"Lenoir-Rhyne University",
"Lesley University",
"Lewis & Clark College",
"Lewis & Clark Law School",
"Lewis University Oak Brook",
"Lewis and Clark Community College Benjamin Godfrey Campus",
"Lewis-Clark State College",
"Liberty University",
"Liberty University School of Law",
"Life Pacific University",
"Lincoln College of Technology",
"Lincoln Memorial University",
"Lindsey Wilson College",
"Linn Benton Community College",
"Lipscomb University",
"Living Arts College",
"Livingstone College",
"Lock Haven University",
"Lone Star College-Houston North Victory",
"Lone Star College-Tomball",
"Long Island University Brooklyn",
"Longwood University",
"Lorain County Community College",
"Loras College",
"Lord Fairfax Community College - Fauquier Campus",
"Los Angeles City College",
"Los Angeles Harbor College",
"Los Angeles Southwest College",
"Los Angeles Trade Technical College - LATTC",
"Los Angeles Valley College",
"Los Medanos College",
"Louisiana College",
"Louisiana Delta Community College",
"Louisiana State University",
"Louisiana State University Eunice",
"Louisiana State University Health Sciences Center New Orleans",
"Louisiana State University in Shreveport",
"Louisiana State University of Alexandria",
"Loyola Marymount University",
"Loyola University Chicago",
"Loyola University Maryland",
"Loyola University New Orleans",
"Lubbock Christian University",
"Luzerne County Community College",
"Lynn University",
"Lyon College",
"MACC - Moberly",
"MSU Denver",
"MTI College",
"Macalester College",
"Macedonian Orthodox Church Sv Kiril i Metodij",
"Macomb Community College",
"Madison Area Technical College",
"Madisonville Community College (North Campus)",
"Maharishi International University",
"Maine Media Workshop",
"Malone University",
"Manchester Community College",
"Manchester University",
"Manhattanville College",
"Mansfield University of Pennsylvania",
"Marian University",
"Marian University Indianapolis",
"Marietta College",
"Marine Corps University",
"Marion Military Institute",
"Marist College",
"Marquette University",
"Marshall Business School, USC",
"Marshall University",
"Marshalltown Community College",
"Martin School of Public Policy and Administration",
"Mary Baldwin University",
"Marymount Manhattan College",
"Marymount University",
"Maryville College",
"Maryville University",
"Marywood University",
"Massachusetts College of Art and Design",
"Massachusetts Institute of Technology",
"Massachusetts Maritime Academy",
"Massasoit Community College",
"Maurer School of Law",
"Maxwell Air Force Base",
"Mayland Community College",
"McDaniel College",
"McHenry County College",
"McKendree University",
"McMurry University",
"McNeese State University",
"Meadville Lombard Theological School",
"Medical College of Georgia",
"Medill School of Journalism, Media, Integrated Marketing Communications",
"Meharry Medical College",
"Merced College",
"Mercer County Community College",
"Mercyhurst University",
"Meredith College",
"Merrimack College",
"Merritt Community College",
"Mesa Community College",
"Messiah University",
"Methodist Theological School",
"Metropolitan Christian University of Chicago",
"Metropolitan College of New York",
"Metropolitan Community College",
"Metropolitan Community College - Maple Woods",
"Metropolitan State University",
"Miami Dade College",
"Miami International University of Art & Design",
"Miami Lakes Educational Center",
"Miami University",
"MidAmerica Nazarene University",
"Middle Georgia State University - Cochran Campus",
"Middle Tennessee State University",
"Middlebury College",
"Middlebury Institute of International Studies at Monterey",
"Middlesex College",
"Middlesex Community College",
"Middlesex County Academy for Science, Mathematics & Engineering Technologies",
"Midland College",
"Midlands Technical College - Northeast Campus",
"Midway University",
"Midwestern Baptist College",
"Millikan High School",
"Millikin University",
"Millsaps College",
"Milwaukee Area Technical College Downtown Milwaukee Campus",
"Milwaukee School of Engineering",
"Mineral Area College",
"Minneapolis College",
"Minnesota State University, Mankato",
"Minot State University",
"MiraCosta College",
"Mission College",
"Mississippi Delta Community College",
"Mississippi State University",
"Mississippi University for Women",
"Missouri Baptist University",
"Missouri Southern State University",
"Missouri State University",
"Missouri State University-West Plains",
"Missouri University of Science and Technology",
"Monmouth College",
"Monmouth University",
"Monroe College",
"Montana State University",
"Montana Technological University",
"Montclair State University",
"Monterey Peninsula College",
"Montessori Foundations of Chicago",
"Montgomery County Community College",
"Montreat College",
"Moody Bible Institute",
"Moorpark College",
"Moraine Valley Community College",
"Moravian University",
"Morehead State University",
"Morehouse College",
"Morningside University",
"Morris College",
"Motion Picture Institute",
"Motlow State Community College Smyrna Campus",
"Mott Community College",
"Mount Holyoke College",
"Mount Mary University",
"Mount Saint Mary College",
"Mount St. Joseph University",
"Mount St. Mary's University",
"Mountwest Community & Technical College",
"Mt. Hood Community College",
"Mt. San Antonio College",
"Mt. San Jacinto College",
"Mueller Hall",
"Muhlenberg College",
"Mullins High School",
"Musicians Institute",
"Muskegon Community College",
"Muskingum University",
"NCTC North Central Texas College - Gainesville Campus",
"NHTI-Concord's Community College",
"NIACC - North Iowa Area Community College",
"NYU School of Law",
"Naperville North High School",
"Nashotah House Theological Seminary",
"Nashua Community College",
"Nashville State Community College",
"Nashville State Technical",
"National Intelligence University",
"National University of Health Sciences",
"Navarro College",
"Neumont College of Computer Science",
"Nevada State College",
"New Charter University",
"New College Franklin",
"New College of Florida",
"New England College",
"New England Law | Boston",
"New England School of Communications",
"New England School of Photography",
"New Horizons",
"New Jersey City University",
"New Jersey Institute of Technology",
"New Mexico Highlands University",
"New Mexico Military Institute",
"New York Film Academy | New York",
"New York Institute of Finance",
"New York University",
"New York University Tandon School of Engineering",
"Newbury College Adult & Pro",
"Newman University",
"Niagara University",
"Nichols College",
"Nicolet College",
"Niles West High School",
"Norco College",
"Normandale Community College",
"North Carolina Agricultural and Technical State University",
"North Carolina Central University",
"North Carolina State University",
"North Central Michigan College",
"North Dakota State University",
"North Greenville University",
"North Hagerstown High School",
"North Hennepin Community College",
"North Idaho College",
"North Seattle College",
"NorthWest Arkansas Community College",
"Northampton Community College",
"Northcentral University",
"Northeast Alabama Community College",
"Northeast Community College",
"Northeast State Community College",
"Northeast Wisconsin Technical",
"Northeastern State University",
"Northeastern University",
"Northern Arizona University",
"Northern Michigan University",
"Northern Oklahoma College",
"Northern State University",
"Northern Vermont University - Johnson",
"Northern Virginia Community College - Alexandria Campus",
"Northern Virginia Community College - Annandale Campus",
"Northside College Prep",
"Northwest Florida State College",
"Northwest Mississippi Community College",
"Northwest Missouri State University",
"Northwest Nazarene University",
"Northwest Vista College",
"Northwestern College Bridgeview Campus",
"Northwestern Michigan College",
"Northwestern Oklahoma State University",
"Northwestern State University",
"Northwestern University",
"Northwood University",
"Northwood University - Cedar Hill Campus",
"Notre Dame de Namur University",
"Nova Southeastern University",
"OSF Saint Francis Medical Center",
"Oakmont Regional High School",
"Oakton Community College",
"Ocean County College",
"Oglethorpe University",
"Ohio Dominican University",
"Ohio Northern University",
"Ohio State University Agricultural Technical Institute",
"Ohio University",
"Oklahoma Christian University",
"Oklahoma City Community College",
"Oklahoma City University",
"Old Dominion University",
"Olin College of Engineering",
"Olivet College",
"Olympic College",
"Onondaga Community College",
"Orange Coast College",
"Orange County Community College (SUNY Orange)",
"Oregon State University",
"Otterbein University",
"Owens Community College",
"Ozarks Technical Community College",
"Pace University",
"Pacific College of Health and Science - Massage Therapy & Acupuncture School",
"Pacific McGeorge School of Law",
"Pacific Oaks College in San Jose",
"Palm Beach Atlantic University",
"Palm Beach State College",
"Paradise Valley Community College",
"Park Vista Community High School",
"Parkland College",
"Parsons School of Design | The New School",
"Pasadena City College",
"Passaic County Community College",
"Patrick Henry College",
"Patten University",
"Patterson School of Diplomacy",
"Paul Mitchell The School Atlanta",
"Peace Operations Training Institute",
"Pellissippi State Community College",
"Penn Graduate School of Education",
"Penn State Abington",
"Penn State Altoona",
"Penn State Behrend",
"Penn State Great Valley: School of Graduate Professional Studies",
"Penn State Harrisburg",
"Penn State New Kensington",
"Penn State Scranton",
"Penn State University",
"Penn State Wilkes-Barre",
"Penn Wood High School - Green Avenue Campus",
"Pensacola State College",
"Philander Smith College",
"Phillips Theological Seminary",
"Phoenix College",
"Piedmont University",
"Piedmont Virginia Community College",
"Pierce College",
"Pierce College Fort Steilacoom",
"Pierce College Puyallup",
"Pikes Peak Community College",
"Plaza College",
"Plymouth State University",
"Polk State College",
"Pomona College",
"Portland Community College Cascade",
"Portland State University",
"Post University",
"Prairie State College",
"Pratt Institute",
"Princeton School of Public and International Affairs",
"Princeton Theological Seminary",
"Princeton University",
"Public Media Institute",
"Purchase College",
"Purdue University",
"Purdue University Northwest - Hammond Campus",
"Queens College, City University of New York",
"Quincy University",
"Quinnipiac University",
"Quinsigamond Community College",
"Radford University",
"Randolph-Macon College",
"Rappahannock Community College",
"Raritan Valley Community College",
"Rawls College of Business",
"Reading Area Community College",
"Red Rocks Community College",
"Reed College",
"Reedley College",
"Regent University",
"Rensselaer Polytechnic Institute",
"Reynolds Community College (Parham Campus)",
"Rhode Island College",
"Richard Bland College of William & Mary",
"Richard J. Daley College",
"Richardson High School",
"Richland Northeast High School",
"Rider University",
"Ringling College of Art and Design",
"Rio Salado College",
"Riverside City College",
"Robert Morris University Illinois",
"Rochester Institute of Technology",
"Rock Valley College",
"Rockford University",
"Rocky Mountain College",
"Roger Williams University",
"Rogers State University",
"Rogue Community College - Redwood Campus",
"Rollins College",
"Roosevelt University",
"Rosalind Franklin University of Medicine and Science",
"Rose-Hulman Institute of Technology",
"Rosemont College",
"Rotterdam School of Management, Erasmus University",
"Rowan College of South Jersey Cumberland Campus",
"Rowan-Cabarrus Community College",
"Rush University College of Health Sciences",
"Rust College",
"SIT | School for International Training",
"SLCC",
"SUNY Adirondack",
"SUNY Brockport",
"SUNY Broome Community College",
"SUNY Buffalo State College",
"SUNY College at Old Westbury",
"SUNY College of Environmental Science and Forestry",
"SUNY Corning Community College",
"SUNY Cortland",
"SUNY Empire State College Administrative Offices",
"SUNY Geneseo",
"SUNY Oswego",
"SUNY Potsdam",
"SUNY Schenectady County Community College",
"SUNY Upstate Medical University",
"Sacramento City College",
"Sacred Heart University",
"Saddleback College",
"Saginaw Valley State University",
"Saint Augustine’s University",
"Saint Cloud State University",
"Saint Francis University",
"Saint John's Seminary",
"Saint John's University",
"Saint Joseph's University",
"Saint Leo University",
"Saint Louis University",
"Saint Louis University School of Medicine",
"Saint Mary's College",
"Saint Mary's College of California",
"Saint Paul's College",
"Saint Peter's University",
"Saint Vincent College",
"Saint Xavier University",
"Salem College",
"Salisbury University",
"Salish Kootenai College",
"Salt Institute-Documentary",
"Salve Regina University",
"San Antonio College",
"San Bernardino Valley College",
"San Diego Mesa College",
"San Diego Miramar College",
"San Diego State University",
"San Diego University for Integrative Studies and English School",
"San Francisco Conservatory of Music",
"San Francisco State University",
"San Joaquin Delta College",
"San José City College",
"San José State University",
"Sandra Day O'Connor College of Law",
"Sanford-Brown College - Chicago",
"Santa Ana College",
"Santa Barbara City College",
"Santa Fe College",
"Santa Fe Community College",
"Santa Fe University of Art and Design",
"Santa Monica College",
"Santiago Canyon College",
"Sarah Lawrence College",
"Sauk Valley Community College",
"School of Engineering and Applied Science",
"School of Theology and Ministry",
"School of the Art Institute of Chicago",
"School of the Museum of Fine Arts at Tufts University",
"Schoolcraft College",
"Scripps College",
"Seattle Central College",
"Seattle Pacific University",
"Seton Hall University",
"Seton Hill University",
"Sewanee: The University Of The South",
"Seward County Community College",
"Shasta College",
"Shaw University",
"Shawnee State University",
"Shelton State Community College",
"Shepherd Rams",
"Shippensburg University",
"Siena College",
"Sierra Nevada University",
"Silver School of Social Work",
"Skidmore College",
"Skyline College",
"Slippery Rock University",
"Smith College",
"Soka University of America",
"Sonoma State University",
"South Brunswick High School",
"South Dakota Mines",
"South Georgia State College",
"South Piedmont Community College",
"South Suburban College",
"South Texas College of Law Houston",
"Southeast Community College",
"Southeast Missouri State University",
"Southeastern Baptist Theological Seminary",
"Southeastern Illinois College",
"Southeastern University",
"Southern Connecticut State University",
"Southern Crescent Technical College - Griffin Campus",
"Southern Evangelical Seminary",
"Southern Illinois University",
"Southern Illinois University Edwardsville",
"Southern Maine Community College",
"Southern Methodist University",
"Southern New Hampshire University",
"Southern Oregon University",
"Southern University and A&M College",
"Southern University at New Orleans",
"Southern Virginia University",
"Southern Wesleyan University",
"Southwest Baptist University",
"Southwest Minnesota State University",
"Southwest Mississippi Community College",
"Southwest Tennessee Community College - Union Avenue Campus",
"Southwest Texas Junior College",
"Southwestern Assemblies of God University (SAGU)",
"Southwestern Baptist Theological Seminary",
"Southwestern College",
"Southwestern College - Professional Studies",
"Southwestern Michigan College",
"Southwestern Oklahoma State University Bookstore",
"Spalding University",
"Spartanburg Methodist College",
"Specs Howard School of Media Arts",
"Spelman College",
"Spokane Falls Community College",
"Spoon River College",
"Spring Arbor University",
"Springfield Technical Community College",
"St Gregory's University",
"St John's University Queens Campus",
"St Joseph's College",
"St Patrick High School",
"St. Ambrose University",
"St. Catherine University",
"St. Charles Community College (SCC)",
"St. Clair County Community College",
"St. Edward's University",
"St. Francis de Sales High School",
"St. John Fisher College",
"St. John's College",
"St. John's College of Nursing",
"St. Kates",
"St. Lawrence University",
"St. Louis Christian College",
"St. Louis Community College",
"St. Louis Community College - Meramec",
"St. Mary's College of Maryland",
"St. Mary's University",
"St. Norbert College",
"St. Olaf College",
"St. Petersburg/Gibbs Campus",
"St. Thomas Bobcats",
"Stanford Graduate School of Business",
"Stanford Law School",
"Stanford University",
"Stanly Community College",
"Stark State College",
"State Fair Community College",
"State University of New York at Fredonia",
"State University of New York at New Paltz",
"State University of New York at Plattsburgh",
"Steele Canyon High School",
"Sterling College",
"Stetson University",
"Stevens Institute of Technology",
"Stillman College",
"Stockbridge High School",
"Stone Mountain High School",
"Stonehill College",
"Stony Brook University",
"Stony Brook University Southampton - Gymnasium",
"Strake Jesuit College Preparatory",
"Suffolk County Community College",
"Suffolk County Community College Grant Campus",
"Suffolk University",
"Sul Ross State University",
"Susquehanna University",
"Swarthmore College",
"TUFW",
"Tacoma Community College",
"Talbot School of Theology",
"Talcott Fine Arts and Museum Academy",
"Talladega College",
"Tallahassee Community College",
"Tarrant County College - Northeast Campus",
"Tarrant County College District Office",
"Taylor University",
"Teachers College, Columbia University",
"Temple University",
"Tennessee Wesleyan University",
"Terra State Community College",
"Texas A&M International University",
"Texas A&M University",
"Texas A&M University - Kingsville",
"Texas A&M University Texarkana",
"Texas A&M University-Commerce",
"Texas A&M University-San Antonio",
"Texas Lutheran University",
"Texas State Technical College",
"Texas State University",
"Texas Tech University",
"The American Musical and Dramatic Academy",
"The Art Institute of Atlanta",
"The Art Institute of California - Orange County",
"The Art Institute of Chicago",
"The Art Institute of Colorado",
"The Art Institute of Fort Lauderdale",
"The Art Institute of Jacksonville",
"The Art Institute of Las Vegas",
"The Art Institute of Philadelphia",
"The Art Institute of Pittsburgh",
"The Art Institute of Seattle",
"The Art Institute of Washington",
"The Art Institutes - New York",
"The Bush School of Government and Public Service",
"The City College of New York",
"The College at Southeastern",
"The College of New Jersey",
"The College of New Rochelle",
"The College of Saint Rose",
"The Colony HS Indoor Facility",
"The Cooper Union",
"The Creative Circus",
"The Culinary Institute of America",
"The Evergreen State College",
"The Fletcher School at Tufts University",
"The Illinois Institute of Art - Chicago",
"The King's College",
"The Lee Strasberg Theatre & Film Institute",
"The Los Angeles Film School",
"The Master's University",
"The New School",
"The Ohio State University",
"The Savannah College of Art and Design",
"The Southern Baptist Theological Seminary",
"The University of Akron",
"The University of Alabama",
"The University of Alabama in Huntsville",
"The University of Arizona",
"The University of Baltimore",
"The University of Chicago",
"The University of Chicago Booth School of Business",
"The University of Iowa",
"The University of Memphis Lambuth Campus",
"The University of New Mexico",
"The University of New Orleans",
"The University of Oklahoma",
"The University of Scranton",
"The University of Southern Mississippi",
"The University of Tennessee at Chattanooga",
"The University of Texas Health Science Center at Houston",
"The University of Texas Permian Basin",
"The University of Texas Rio Grande Valley",
"The University of Texas at Austin",
"The University of Texas at El Paso",
"The University of Toledo",
"The University of Utah",
"The University of Western Australia",
"Thiel Audio Products",
"Thomas Aquinas College",
"Thomas Dale High School - Main Campus",
"Thomas Edison State University",
"Thomas Jefferson School of Law",
"Thomas Jefferson University",
"Thomas More University",
"Thomas Nelson Community College",
"Thunderbird School of Global Management",
"Tiffin",
"Tiffin University",
"Tompkins Cortland Community College",
"Tougaloo College",
"Touro College",
"Towson University",
"Trevecca Nazarene University",
"Tri-County Technical College",
"Trident Technical College",
"Trident University",
"Trine University",
"Trinity College",
"Trinity Valley Community College",
"Triton College",
"Troy University",
"Troy University - Fort Walton Beach Support Center",
"Truckee Meadows Community College (TMCC)",
"Truman Hall, Camden County College",
"Truman State University",
"Tufts University",
"Tulane University",
"Tulane University School of Public Health and Tropical Medicine",
"Tulsa Community College Northeast Campus",
"Tuskegee University",
"Tyler Junior College",
"UA - Eller College of Management",
"UALR William H. Bowen School of Law",
"UC Hastings College of the Law",
"UCSD-RIMAC ARENA",
"UChicago Medicine",
"US Army War College",
"US Naval War College",
"UTMB Health - University of Texas Medical Branch at Galveston",
"UW-Green Bay | Marinette Campus",
"UW-Milwaukee at Washington County",
"UW-Milwaukee at Waukesha",
"UW-Oshkosh at Fox Cities",
"UW-Platteville Baraboo Sauk County",
"UW-Platteville at Richland",
"UW-Stevens Point at Wausau",
"UW-Whitewater at Rock County",
"UWM CLS Department of History",
"Ultimate Medical Academy (Online)",
"Union College",
"Union County College",
"Union University",
"United States Coast Guard Academy",
"United States Naval Academy",
"United World College-USA",
"Universal Technical Institute",
"University Of The Southwest",
"University at Albany",
"University at Buffalo",
"University of Advancing Technology",
"University of Akron School of Law",
"University of Alabama at Birmingham",
"University of Arizona Global Campus",
"University of Arkansas",
"University of Arkansas - Fort Smith",
"University of Arkansas Community College at Batesville",
"University of Arkansas Community College at Morrilton",
"University of Arkansas at Little Rock",
"University of Arkansas – Pulaski Technical College",
"University of Bridgeport",
"University of California Irvine",
"University of California Merced",
"University of California San Diego",
"University of California Santa Cruz",
"University of California, Davis",
"University of California, Los Angeles",
"University of California, Riverside",
"University of California, Santa Barbara",
"University of Central Missouri",
"University of Central Oklahoma",
"University of Cincinnati",
"University of Colorado Boulder",
"University of Colorado Colorado Springs",
"University of Colorado Denver",
"University of Connecticut",
"University of Connecticut - Avery Point Campus",
"University of Connecticut-Stamford Campus",
"University of Dallas",
"University of Delaware",
"University of Denver",
"University of Detroit Mercy",
"University of Dubuque",
"University of Evansville",
"University of Florida",
"University of Florida Levin College of Law",
"University of Georgia",
"University of Hartford",
"University of Hawaiʻi System",
"University of Holy Cross",
"University of Houston",
"University of Houston-Clear Lake",
"University of Houston-Downtown (UHD)",
"University of Houston-Victoria",
"University of Illinois Chicago",
"University of Illinois Chicago School of Law",
"University of Illinois Springfield",
"University of Indianapolis",
"University of Kansas",
"University of Kentucky J. David Rosenberg College of Law",
"University of Louisiana Monroe",
"University of Louisiana at Lafayette",
"University of Maine",
"University of Maine Farmington",
"University of Maine at Machias",
"University of Mary",
"University of Mary Washington",
"University of Maryland",
"University of Maryland Eastern Shore",
"University of Maryland Global Campus",
"University of Maryland School of Law",
"University of Maryland, Baltimore County",
"University of Massachusetts Amherst",
"University of Massachusetts Boston",
"University of Massachusetts Dartmouth",
"University of Massachusetts Lowell",
"University of Memphis",
"University of Metaphysical Sciences",
"University of Miami",
"University of Michigan",
"University of Michigan Hospital",
"University of Michigan Law School",
"University of Michigan-Dearborn",
"University of Minnesota",
"University of Minnesota Duluth",
"University of Minnesota Law School",
"University of Minnesota, Morris",
"University of Mississippi",
"University of Mississippi Medical Center",
"University of Missouri",
"University of Missouri-Kansas City Volker Campus",
"University of Montana",
"University of Mount Olive",
"University of Mount Union",
"University of Nebraska Omaha",
"University of Nebraska-Lincoln",
"University of Nevada, Las Vegas",
"University of Nevada, Reno",
"University of New Haven",
"University of North Carolina Greensboro",
"University of North Carolina Wilmington",
"University of North Carolina at Charlotte",
"University of North Carolina at Pembroke",
"University of North Dakota",
"University of North Florida",
"University of North Georgia",
"University of North Texas",
"University of Northwestern – St. Paul",
"University of Notre Dame",
"University of Oklahoma College of Law",
"University of Oregon",
"University of Pennsylvania",
"University of Phoenix",
"University of Pittsburgh",
"University of Pittsburgh at Bradford",
"University of Providence",
"University of Rhode Island",
"University of Rhode Island Providence Campus",
"University of Richmond",
"University of Rio Grande",
"University of SC Union",
"University of Saint Francis",
"University of San Francisco",
"University of Santa Monica",
"University of Science and Arts of Oklahoma",
"University of Sioux Falls",
"University of South Alabama",
"University of South Carolina",
"University of South Carolina Salkehatchie",
"University of South Carolina Upstate",
"University of South Florida",
"University of South Florida St. Petersburg Campus",
"University of Southern California",
"University of Southern Indiana",
"University of Southern Maine",
"University of St. Thomas",
"University of Tennessee",
"University of Tennessee College of Law",
"University of Tennessee Southern",
"University of Texas at Arlington",
"University of Texas at Dallas",
"University of Texas at San Antonio",
"University of Utah S.J. Quinney College of Law",
"University of Vermont",
"University of Virginia School of Law",
"University of Virginia: Department of Politics",
"University of West Alabama",
"University of West Florida",
"University of West Georgia",
"University of Wisconsin-Green Bay",
"University of Wisconsin-Milwaukee",
"University of Wisconsin-Platteville",
"University of Wisconsin-River Falls",
"University of Wisconsin-Stout",
"University of Wisconsin-Superior",
"University of Wisconsin-Whitewater",
"University of Wisconsin–Eau Claire",
"University of Wisconsin–La Crosse",
"University of Wisconsin–Stevens Point",
"University of Wyoming",
"University of the Cumberlands",
"University of the Ozarks",
"University of the Pacific",
"University of the Sciences in Philadelphia",
"University of the West",
"Urbana University",
"Ursinus College",
"Utah State University",
"Utah State University Eastern",
"Utah Valley University",
"Utica College",
"Valdosta State University",
"Valencia College",
"Valparaiso University",
"Van Andel Graduate School of Statesmanship",
"Vanderbilt Law School",
"Vanderbilt University",
"Vanderbilt University’s Peabody College",
"Varsity College Planning",
"Vassar College",
"Ventura College",
"Vermilion Community College",
"Vermont College of Fine Arts",
"Vermont Law School",
"Vermont Technical College",
"Victoria College",
"Villanova University",
"Villanova University Charles Widger School of Law",
"Vincennes University",
"Vincennes University Jasper",
"Virginia Commonwealth University",
"Virginia Military Institute",
"Virginia Polytechnic Institute and State University",
"Virginia Western Community College",
"Voorhees College",
"Wabash College",
"Wagner College",
"Wake Forest University",
"Wake Forest University School of Law",
"Wake Technical Community College- Southern Wake Campus",
"Walden University",
"Waldorf University",
"Walla Walla University",
"Wallace State Community College",
"Walsh College",
"Walsh University",
"Walters State Community College",
"Warren Wilson College",
"Wartburg College",
"Washburn University",
"Washburne Culinary & Hospitality Institute",
"Washington & Jefferson College",
"Washington Adventist University",
"Washington University in St. Louis",
"Washington and Lee University",
"Washtenaw Community College",
"Waubonsee Community College",
"Wayland Baptist University",
"Wayne State College",
"Wayne State University",
"Waynesburg University",
"Webber International University",
"Weber State University",
"Wellesley College",
"Wells College",
"Wenatchee Valley College - Omak",
"Wendell Phillips Academy High School",
"Wentworth Institute of Technology",
"Wesley College",
"West Chester University of Pennsylvania",
"West Coast University",
"West Hills Community College District",
"West Liberty University",
"West Los Angeles College",
"West Texas A&M University",
"West Virginia Northern Community College Wheeling Campus",
"West Virginia University",
"Westchester Community College",
"Western Carolina University",
"Western Colorado University",
"Western Connecticut State University",
"Western Governors University",
"Western Illinois University",
"Western Illinois University - Quad Cities",
"Western Michigan University",
"Western Michigan University Thomas M. Cooley Law School",
"Western Nevada College",
"Western New England University",
"Western Washington University",
"Westfield State University",
"Westminster College",
"Westminster Seminary California",
"Westminster Theological Seminary",
"Westmont College",
"Whatcom Community College",
"Wheaton College",
"Wheeling University",
"Whitefield College & Theologic",
"Whitworth University",
"Wichita State University",
"Widener University",
"Wilberforce University",
"Wilbur Wright College",
"Wiley College",
"Wilkes University",
"Willamette University",
"William & Mary",
"William Carey University",
"William Howard Taft University",
"William Jessup University",
"William Jewell College",
"William Paterson University",
"William Peace University",
"Williams Baptist University",
"Williams College",
"Wilmington College",
"Wilmington University",
"Wilson College",
"Winona State University",
"Winston-Salem State University",
"Winthrop University",
"Woodbury University",
"Wor-Wic Community College",
"Worcester Polytechnic Institute",
"Wright State University",
"Wytheville Community College",
"Xavier Musketeers",
"Xavier University of Louisiana",
"Yale Divinity School",
"Yale Law School",
"Yale University",
"Yankton College",
"Yavapai College",
"Yeshiva Gedolah College",
"Yeshiva University",
"York College",
"Young Harris College",
"Youngstown State University",
"Ziibiwing Center",
"Zion-Benton Township High School"
   ];
   
  $("[fs-field-validation-name='3.1.1) University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
});
